version: '3.8'

services:
  client:
    build: . # Le Dockerfile est dans le mÃªme dossier (client/)
    container_name: land_registry_client
    restart: always
    ports:
      - "5173:80" # On map le port 80 (Nginx) vers 5173 (votre PC)
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge